name: build

on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Pack
        run: |
            $VERSION = "1.0.0-alpha.${{ github.run_number }}"
            dotnet pack MauiYoutubeIframe -c Release -p:Version=$VERSION
      - uses: actions/upload-artifact@v1
        with:
          name: Output
          path: '**/*.nupkg'
